//
//  SmartGoalEngine.swift
//  PesoTracker
//
//  Created by Kiro on 19/07/25.
//

import Foundation

// MARK: - Smart Goal Engine

class SmartGoalEngine {
    private let progressPredictor = ProgressPredictor()
    
    // MARK: - Main Goal Generation Methods
    
    /// Generate short-term milestone goals from a main goal
    func generateShortTermGoals(
        from mainGoal: Goal,
        currentWeight: Double,
        weightEntries: [WeightEntry] = []
    ) -> [SmartGoal] {
        
        let milestones = calculateOptimalMilestones(
            startWeight: currentWeight,
            targetWeight: mainGoal.targetWeight,
            timeframe: getTimeInterval(from: mainGoal.targetDate),
            weightEntries: weightEntries
        )
        
        return milestones.enumerated().map { index, milestone in
            SmartGoal(
                id: 0, // Will be assigned by backend
                type: .shortTerm,
                targetWeight: milestone.targetWeight,
                targetDate: formatDate(milestone.targetDate),
                isAutoGenerated: true,
                parentGoalId: mainGoal.id,
                milestoneNumber: index + 1,
                createdAt: formatDate(Date()),
                achievedAt: nil
            )
        }
    }
    
    /// Calculate optimal milestone spacing and timing
    func calculateOptimalMilestones(
        startWeight: Double,
        targetWeight: Double,
        timeframe: TimeInterval,
        weightEntries: [WeightEntry] = []
    ) -> [Milestone] {
        
        let totalWeightToLose = startWeight - targetWeight
        guard totalWeightToLose > 0 else { return [] }
        
        // Determine milestone spacing (2-5kg intervals)
        let milestoneSpacing = calculateMilestoneSpacing(totalWeightToLose: totalWeightToLose)
        
        // Calculate number of milestones needed
        let numberOfMilestones = Int(ceil(totalWeightToLose / milestoneSpacing))
        
        // Get healthy weight loss rate (0.5-1kg per week)
        let healthyWeeklyRate = getHealthyWeightLossRate(
            totalWeight: totalWeightToLose,
            timeframe: timeframe,
            weightEntries: weightEntries
        )
        
        var milestones: [Milestone] = []
        let startDate = Date()
        
        for i in 1...numberOfMilestones {
            let milestoneWeight = startWeight - (Double(i) * milestoneSpacing)
            let finalWeight = max(milestoneWeight, targetWeight)
            
            // Calculate target date for this milestone
            let weeksNeeded = (Double(i) * milestoneSpacing) / healthyWeeklyRate
            let targetDate = startDate.addingTimeInterval(weeksNeeded * 7 * 24 * 60 * 60)
            
            milestones.append(Milestone(
                targetWeight: finalWeight,
                targetDate: targetDate,
                milestoneNumber: i
            ))
            
            // Stop if we've reached the target weight
            if finalWeight <= targetWeight {
                break
            }
        }
        
        return milestones
    }
    
    /// Adjust goal timeline based on user progress
    func adjustGoalTimeline(
        goals: [Goal],
        currentWeight: Double,
        weightEntries: [WeightEntry]
    ) -> [SmartGoal] {
        
        guard let mainGoal = goals.first(where: { $0.type == .main }) else {
            return []
        }
        
        // Get current progress prediction
        let targetDate = parseDate(mainGoal.targetDate) ?? Date()
        let prediction = progressPredictor.generatePrediction(
            currentWeight: currentWeight,
            targetWeight: mainGoal.targetWeight,
            targetDate: targetDate,
            weightEntries: weightEntries
        )
        
        // If user is significantly ahead or behind, regenerate milestones
        switch prediction.insight {
        case .aheadOfSchedule(let days) where days > 14:
            return regenerateMilestones(mainGoal: mainGoal, currentWeight: currentWeight, adjustment: .accelerated)
            
        case .behindSchedule(let days) where days > 14:
            return regenerateMilestones(mainGoal: mainGoal, currentWeight: currentWeight, adjustment: .extended)
            
        default:
            // No significant adjustment needed
            return goals.compactMap { goal in
                SmartGoal(from: goal)
            }
        }
    }
    
    /// Check if maintenance goal should be created
    func shouldCreateMaintenanceGoal(
        currentWeight: Double,
        mainGoal: Goal,
        weightEntries: [WeightEntry]
    ) -> Bool {
        
        // Check if main goal is achieved
        guard mainGoal.isAchieved(currentWeight: currentWeight) else {
            return false
        }
        
        // Check if user has been at target weight for at least a week
        let recentEntries = weightEntries.suffix(7)
        let allAtTarget = recentEntries.allSatisfy { entry in
            abs(entry.weight - mainGoal.targetWeight) <= 0.5
        }
        
        return allAtTarget && recentEntries.count >= 3
    }
    
    /// Create a maintenance goal
    func createMaintenanceGoal(from mainGoal: Goal) -> SmartGoal {
        let maintenanceDate = Calendar.current.date(byAdding: .month, value: 6, to: Date()) ?? Date()
        
        return SmartGoal(
            id: 0,
            type: .maintenance,
            targetWeight: mainGoal.targetWeight,
            targetDate: formatDate(maintenanceDate),
            isAutoGenerated: true,
            parentGoalId: mainGoal.id,
            milestoneNumber: nil,
            createdAt: formatDate(Date()),
            achievedAt: nil
        )
    }
    
    // MARK: - Helper Methods
    
    private func calculateMilestoneSpacing(totalWeightToLose: Double) -> Double {
        switch totalWeightToLose {
        case 0...5:
            return 1.0 // 1kg milestones for small goals
        case 5...15:
            return 2.5 // 2.5kg milestones for medium goals
        case 15...30:
            return 5.0 // 5kg milestones for large goals
        default:
            return 7.5 // 7.5kg milestones for very large goals
        }
    }
    
    private func getHealthyWeightLossRate(
        totalWeight: Double,
        timeframe: TimeInterval,
        weightEntries: [WeightEntry]
    ) -> Double {
        
        // If we have historical data, use it to inform the rate
        if weightEntries.count >= 3 {
            let currentRate = abs(progressPredictor.calculateAverageWeightLoss(from: weightEntries))
            
            // Ensure it's within healthy bounds (0.5-1kg per week)
            let healthyRate = max(0.5, min(currentRate, 1.0))
            return healthyRate
        }
        
        // Calculate based on timeframe and total weight
        let weeksAvailable = timeframe / (7 * 24 * 60 * 60)
        let requiredRate = totalWeight / weeksAvailable
        
        // Ensure it's within healthy bounds
        return max(0.5, min(requiredRate, 1.0))
    }
    
    private func regenerateMilestones(
        mainGoal: Goal,
        currentWeight: Double,
        adjustment: TimelineAdjustment
    ) -> [SmartGoal] {
        
        let originalTimeframe = getTimeInterval(from: mainGoal.targetDate)
        let adjustedTimeframe: TimeInterval
        
        switch adjustment {
        case .accelerated:
            adjustedTimeframe = originalTimeframe * 0.8 // 20% faster
        case .extended:
            adjustedTimeframe = originalTimeframe * 1.3 // 30% longer
        case .normal:
            adjustedTimeframe = originalTimeframe
        }
        
        let milestones = calculateOptimalMilestones(
            startWeight: currentWeight,
            targetWeight: mainGoal.targetWeight,
            timeframe: adjustedTimeframe
        )
        
        return milestones.enumerated().map { index, milestone in
            SmartGoal(
                id: 0,
                type: .shortTerm,
                targetWeight: milestone.targetWeight,
                targetDate: formatDate(milestone.targetDate),
                isAutoGenerated: true,
                parentGoalId: mainGoal.id,
                milestoneNumber: index + 1,
                createdAt: formatDate(Date()),
                achievedAt: nil
            )
        }
    }
    
    private func getTimeInterval(from dateString: String) -> TimeInterval {
        guard let date = parseDate(dateString) else {
            return 90 * 24 * 60 * 60 // Default to 90 days
        }
        return date.timeIntervalSinceNow
    }
    
    private func parseDate(_ dateString: String) -> Date? {
        let formatter = DateFormatter()
        let formats = [
            "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
            "yyyy-MM-dd'T'HH:mm:ss'Z'",
            "yyyy-MM-dd"
        ]
        
        for format in formats {
            formatter.dateFormat = format
            if let date = formatter.date(from: dateString) {
                return date
            }
        }
        
        return nil
    }
    
    private func formatDate(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter.string(from: date)
    }
}

// MARK: - Supporting Data Structures

struct Milestone {
    let targetWeight: Double
    let targetDate: Date
    let milestoneNumber: Int
}

enum TimelineAdjustment {
    case accelerated
    case extended
    case normal
}

// MARK: - Smart Goal Recommendations

extension SmartGoalEngine {
    
    /// Get intelligent recommendations for goal creation
    func getGoalRecommendations(
        currentWeight: Double,
        desiredWeight: Double,
        timeframe: TimeInterval
    ) -> LegacyGoalRecommendation {
        
        let totalWeightToLose = currentWeight - desiredWeight
        let weeksAvailable = timeframe / (7 * 24 * 60 * 60)
        let requiredWeeklyRate = totalWeightToLose / weeksAvailable
        
        let recommendation: LegacyRecommendationType
        let adjustedTimeframe: TimeInterval
        let adjustedTarget: Double
        
        if requiredWeeklyRate > 1.0 {
            // Too aggressive
            recommendation = .tooAggressive
            adjustedTimeframe = (totalWeightToLose / 0.8) * 7 * 24 * 60 * 60 // 0.8kg per week
            adjustedTarget = desiredWeight
        } else if requiredWeeklyRate < 0.3 {
            // Too conservative
            recommendation = .tooConservative
            adjustedTimeframe = (totalWeightToLose / 0.6) * 7 * 24 * 60 * 60 // 0.6kg per week
            adjustedTarget = desiredWeight
        } else {
            // Just right
            recommendation = .optimal
            adjustedTimeframe = timeframe
            adjustedTarget = desiredWeight
        }
        
        return LegacyGoalRecommendation(
            type: recommendation,
            recommendedTimeframe: adjustedTimeframe,
            recommendedTarget: adjustedTarget,
            expectedWeeklyRate: min(max(requiredWeeklyRate, 0.5), 1.0),
            milestoneCount: Int(ceil(totalWeightToLose / calculateMilestoneSpacing(totalWeightToLose: totalWeightToLose)))
        )
    }
}

// Note: GoalRecommendation and RecommendationType are now defined in SmartGoalIntelligence.swift

struct LegacyGoalRecommendation {
    let type: LegacyRecommendationType
    let recommendedTimeframe: TimeInterval
    let recommendedTarget: Double
    let expectedWeeklyRate: Double
    let milestoneCount: Int
    
    var formattedTimeframe: String {
        let weeks = Int(recommendedTimeframe / (7 * 24 * 60 * 60))
        if weeks < 4 {
            return "\(weeks) semanas"
        } else {
            let months = weeks / 4
            return "\(months) meses"
        }
    }
    
    var recommendationText: String {
        switch type {
        case .optimal:
            return "¡Perfecto! Tu meta es realista y saludable."
        case .tooAggressive:
            return "Tu meta es muy ambiciosa. Te recomendamos extender el tiempo."
        case .tooConservative:
            return "Puedes ser más ambicioso. Considera acortar el tiempo."
        }
    }
}

enum LegacyRecommendationType {
    case optimal
    case tooAggressive
    case tooConservative
}