//
//  Goal.swift
//  PesoTracker
//
//  Created by Steven Coaila Zaa on 17/07/25.
//

import Foundation

// MARK: - Goal Types
enum GoalType: String, CaseIterable, Codable {
    case main = "main"           // Long-term primary goal
    case shortTerm = "short"     // Auto-generated milestones
    case maintenance = "maintenance" // Weight maintenance
    
    var priority: Int {
        switch self {
        case .main: return 1
        case .shortTerm: return 2
        case .maintenance: return 3
        }
    }
    
    var displayName: String {
        switch self {
        case .main: return "Main Goal"
        case .shortTerm: return "Milestone"
        case .maintenance: return "Maintenance"
        }
    }
    
    var emoji: String {
        switch self {
        case .main: return "🏆"
        case .shortTerm: return "🎯"
        case .maintenance: return "⚖️"
        }
    }
}

struct Goal: Codable, Identifiable {
    let id: Int
    let userId: Int
    let targetWeight: Double
    let targetDate: String
    let type: GoalType
    let isAutoGenerated: Bool
    let parentGoalId: Int?       // Links to main goal for short-term goals
    let milestoneNumber: Int?    // Which milestone (1st, 2nd, etc.)
    let createdAt: String?
    let updatedAt: String?
    
    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case targetWeight = "target_weight"
        case targetDate = "target_date"
        case type
        case isAutoGenerated = "is_auto_generated"
        case parentGoalId = "parent_goal_id"
        case milestoneNumber = "milestone_number"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
    
    // Custom decoder to handle target_weight as string from API
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        
        id = try container.decode(Int.self, forKey: .id)
        userId = try container.decode(Int.self, forKey: .userId)
        targetDate = try container.decode(String.self, forKey: .targetDate)
        type = try container.decodeIfPresent(GoalType.self, forKey: .type) ?? .main
        isAutoGenerated = try container.decodeIfPresent(Bool.self, forKey: .isAutoGenerated) ?? false
        parentGoalId = try container.decodeIfPresent(Int.self, forKey: .parentGoalId)
        milestoneNumber = try container.decodeIfPresent(Int.self, forKey: .milestoneNumber)
        createdAt = try container.decodeIfPresent(String.self, forKey: .createdAt)
        updatedAt = try container.decodeIfPresent(String.self, forKey: .updatedAt)
        
        // Handle targetWeight as either String or Double
        if let weightString = try? container.decode(String.self, forKey: .targetWeight) {
            targetWeight = Double(weightString) ?? 0.0
        } else {
            targetWeight = try container.decode(Double.self, forKey: .targetWeight)
        }
    }
    
    // Custom encoder for sending data back to API
    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        
        try container.encode(id, forKey: .id)
        try container.encode(userId, forKey: .userId)
        try container.encode(targetWeight, forKey: .targetWeight) // Send as Double
        try container.encode(targetDate, forKey: .targetDate)
        try container.encode(type, forKey: .type)
        try container.encode(isAutoGenerated, forKey: .isAutoGenerated)
        try container.encodeIfPresent(parentGoalId, forKey: .parentGoalId)
        try container.encodeIfPresent(milestoneNumber, forKey: .milestoneNumber)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
    
    // Computed properties
    var isMainGoal: Bool { type == .main }
    var isShortTermGoal: Bool { type == .shortTerm }
    var isMaintenanceGoal: Bool { type == .maintenance }
    
    var displayTitle: String {
        switch type {
        case .main:
            return "Main Goal: \(formattedTargetWeight)"
        case .shortTerm:
            if let milestone = milestoneNumber {
                return "Milestone #\(milestone): \(formattedTargetWeight)"
            } else {
                return "Milestone: \(formattedTargetWeight)"
            }
        case .maintenance:
            return "Maintain: \(formattedTargetWeight)"
        }
    }
    
    var formattedTargetWeight: String {
        return String(format: "%.1f kg", targetWeight)
    }
    
    var formattedTargetDate: String {
        let dateFormatter = DateFormatter()
        // Try different date formats that the API might return
        let formats = [
            "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
            "yyyy-MM-dd'T'HH:mm:ss'Z'",
            "yyyy-MM-dd"
        ]
        
        for format in formats {
            dateFormatter.dateFormat = format
            if let parsedDate = dateFormatter.date(from: targetDate) {
                let displayFormatter = DateFormatter()
                displayFormatter.dateFormat = "MMM dd, yyyy"
                return displayFormatter.string(from: parsedDate)
            }
        }
        
        // If no format works, return the original string
        return targetDate
    }
}

struct GoalResponse: Codable {
    let data: [Goal]
}

struct CreateGoalRequest: Codable {
    let targetWeight: Double
    let targetDate: String
    let type: GoalType?
    let isAutoGenerated: Bool?
    let parentGoalId: Int?
    let milestoneNumber: Int?
    
    enum CodingKeys: String, CodingKey {
        case targetWeight = "target_weight"
        case targetDate = "target_date"
        case type
        case isAutoGenerated = "is_auto_generated"
        case parentGoalId = "parent_goal_id"
        case milestoneNumber = "milestone_number"
    }
    
    // Convenience initializer for simple goals (backward compatibility)
    init(targetWeight: Double, targetDate: String) {
        self.targetWeight = targetWeight
        self.targetDate = targetDate
        self.type = .main
        self.isAutoGenerated = false
        self.parentGoalId = nil
        self.milestoneNumber = nil
    }
    
    // Full initializer for smart goals
    init(
        targetWeight: Double,
        targetDate: String,
        type: GoalType,
        isAutoGenerated: Bool = false,
        parentGoalId: Int? = nil,
        milestoneNumber: Int? = nil
    ) {
        self.targetWeight = targetWeight
        self.targetDate = targetDate
        self.type = type
        self.isAutoGenerated = isAutoGenerated
        self.parentGoalId = parentGoalId
        self.milestoneNumber = milestoneNumber
    }
}

struct CreateGoalResponse: Codable {
    let message: String
    let data: Goal
}

// MARK: - Smart Goal Extensions

/// Enhanced goal structure for smart goal generation and management
struct SmartGoal: Codable, Identifiable {
    let id: Int
    let type: GoalType
    let targetWeight: Double
    let targetDate: String
    let isAutoGenerated: Bool
    let parentGoalId: Int?
    let milestoneNumber: Int?
    let createdAt: String?
    let achievedAt: String?
    
    // Computed properties
    var isAchieved: Bool { achievedAt != nil }
    var isMainGoal: Bool { type == .main }
    var displayTitle: String {
        switch type {
        case .main:
            return "🏆 Main Goal: \(formattedTargetWeight)"
        case .shortTerm:
            if let milestone = milestoneNumber {
                return "🎯 Milestone #\(milestone): \(formattedTargetWeight)"
            } else {
                return "🎯 Milestone: \(formattedTargetWeight)"
            }
        case .maintenance:
            return "⚖️ Maintain: \(formattedTargetWeight)"
        }
    }
    
    var formattedTargetWeight: String {
        return String(format: "%.1f kg", targetWeight)
    }
    
    var formattedTargetDate: String {
        let dateFormatter = DateFormatter()
        let formats = [
            "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
            "yyyy-MM-dd'T'HH:mm:ss'Z'",
            "yyyy-MM-dd"
        ]
        
        for format in formats {
            dateFormatter.dateFormat = format
            if let parsedDate = dateFormatter.date(from: targetDate) {
                let displayFormatter = DateFormatter()
                displayFormatter.dateFormat = "MMM dd, yyyy"
                return displayFormatter.string(from: parsedDate)
            }
        }
        
        return targetDate
    }
    
    /// Convert from Goal to SmartGoal
    init(from goal: Goal, achievedAt: String? = nil) {
        self.id = goal.id
        self.type = goal.type
        self.targetWeight = goal.targetWeight
        self.targetDate = goal.targetDate
        self.isAutoGenerated = goal.isAutoGenerated
        self.parentGoalId = goal.parentGoalId
        self.milestoneNumber = goal.milestoneNumber
        self.createdAt = goal.createdAt
        self.achievedAt = achievedAt
    }
    
    /// Full initializer for creating new SmartGoals
    init(
        id: Int,
        type: GoalType,
        targetWeight: Double,
        targetDate: String,
        isAutoGenerated: Bool,
        parentGoalId: Int?,
        milestoneNumber: Int?,
        createdAt: String?,
        achievedAt: String?
    ) {
        self.id = id
        self.type = type
        self.targetWeight = targetWeight
        self.targetDate = targetDate
        self.isAutoGenerated = isAutoGenerated
        self.parentGoalId = parentGoalId
        self.milestoneNumber = milestoneNumber
        self.createdAt = createdAt
        self.achievedAt = achievedAt
    }
}

// MARK: - Goal Hierarchy Management

struct GoalHierarchy {
    let mainGoal: Goal?
    let shortTermGoals: [Goal]
    let maintenanceGoals: [Goal]
    
    var allGoals: [Goal] {
        var goals: [Goal] = []
        if let main = mainGoal { goals.append(main) }
        goals.append(contentsOf: shortTermGoals)
        goals.append(contentsOf: maintenanceGoals)
        return goals
    }
    
    var activeGoals: [Goal] {
        allGoals.filter { goal in
            // A goal is active if it's not achieved yet
            // We'll determine achievement status based on current weight vs target
            true // For now, we'll handle achievement logic elsewhere
        }
    }
    
    var currentMilestone: Goal? {
        // Return the next unachieved short-term goal
        shortTermGoals.first // Simplified for now
    }
    
    init(from goals: [Goal]) {
        self.mainGoal = goals.first { $0.type == .main }
        self.shortTermGoals = goals.filter { $0.type == .shortTerm }.sorted { 
            ($0.milestoneNumber ?? 0) < ($1.milestoneNumber ?? 0) 
        }
        self.maintenanceGoals = goals.filter { $0.type == .maintenance }
    }
}

// MARK: - Goal Utilities

extension Goal {
    /// Check if this goal should be considered achieved based on current weight
    func isAchieved(currentWeight: Double) -> Bool {
        // For weight loss goals, achieved when current weight <= target weight
        // For maintenance goals, achieved when within ±0.5kg of target
        switch type {
        case .main, .shortTerm:
            return currentWeight <= targetWeight
        case .maintenance:
            return abs(currentWeight - targetWeight) <= 0.5
        }
    }
    
    /// Calculate progress percentage towards this goal
    func progressPercentage(currentWeight: Double, startWeight: Double) -> Double {
        guard startWeight != targetWeight else { return 100.0 }
        
        let totalDistance = abs(startWeight - targetWeight)
        let currentDistance = abs(startWeight - currentWeight)
        let progress = (currentDistance / totalDistance) * 100.0
        
        return min(max(progress, 0.0), 100.0)
    }
    
    /// Get days remaining until target date
    var daysRemaining: Int? {
        let dateFormatter = DateFormatter()
        let formats = [
            "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
            "yyyy-MM-dd'T'HH:mm:ss'Z'",
            "yyyy-MM-dd"
        ]
        
        for format in formats {
            dateFormatter.dateFormat = format
            if let targetDate = dateFormatter.date(from: self.targetDate) {
                let calendar = Calendar.current
                let days = calendar.dateComponents([.day], from: Date(), to: targetDate).day
                return days
            }
        }
        
        return nil
    }
    
    /// Check if goal is overdue
    var isOverdue: Bool {
        guard let days = daysRemaining else { return false }
        return days < 0
    }
}